### ISSUE TITLE
Compile with clang-14 error

### ISSUE THREAD

**Issue by LeCmnGend** [vijaymalav564/vortex-clang#2]
My clang-13 (proton kdrag0n compile fine)

       $
        root@LeCmnGend:~/test/gg# ~/tc/proton/clang-13/bin/clang --version
        Proton clang version 13.0.0 (https://github.com/llvm/llvm-project b4fd512c36ca344a3ff69350219e8b0a67e9472a)
        Target: x86_64-unknown-linux-gnu
        Thread model: posix
        InstalledDir: /root/tc/proton/clang-13/bin

While my clang-14 show :

        $ error: unable to create target: 'No available targets are compatible with triple "x86_64-unknown-linux-gnu"'
        
        $
        root@LeCmnGend:~/test/gg# clang --version
        Vortex clang version 14.0.0 (https://github.com/llvm/llvm-project e581841e8cf46109acea92e1acb661c404fa62b9)
        Target: x86_64-unknown-linux-gnu
        Thread model: posix
        InstalledDir: /usr/bin

i think the link to **installedDir ** of my 14 not updated as the folder i place it, so it cause error,
hope you help me
my kernel: (i run b14.sh)

      $ https://github.com/LeCmnGend/kernel_xiaomi_ginkgo/tree/clang-14

**Comment by vijaymalav564** [comment]
I added support for x86 target too with this clang tc that should fix ur issue.

**Comment by LeCmnGend** [comment]
> I added support for x86 target too with this clang tc that should fix ur issue.

thank you for helping me (noob). lol

**Comment by LeCmnGend** [comment]
Another problems me meet (do i need to place similar dir like readme.md ?)
/root/tc/proton/clang-14/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /root/tc/proton/clang-14/bin/clang)

**Comment by vijaymalav564** [comment]
upgrade ur glibc package to v2.32

**Comment by LeCmnGend** [comment]
Thank for your support sir. I install clang 13 from llvm.org and it have all glibc i think (not work with audio apt get clang gcc). Apt get version is too old
